apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-sqldump-cronjob
  namespace: hedgedoc
  labels:
    app: {{ .Release.Name }}
spec:
  schedule: "{{ .Values.backupSQLDumpSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-sqldump
            image: docker.io/bitnami/postgresql:15.2.0-debian-11-r14
            command: [ "/bin/sh", "-c", "--" ]
            args: [ "echo starting {{ .Release.Name }}-sqldump;
            set -x;
            date;
            rm -rf /backup/hedgedoc-sqldump-*.sql.gz;
            date;
            export TODAY=$(date -I);
            cd /backup;
            pg_dump -h $POSTGRES_HOST -U $POSTGRES_USER | gzip -c > hedgedoc-sqldump-$TODAY.sql.gz;
            date;
			ls -lah /backup/hedgedoc-sqldump-*.sql.gz;
            echo finished {{ .Release.Name }}-sqldump"]
            imagePullPolicy: IfNotPresent
            #imagePullPolicy: Always
            env:
            - name: POSTGRES_HOST
              value: {{ .Values.pgHost }}
            - name: POSTGRES_USER
              value: {{ .Values.pgUser }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgPasswordSecret }}
                  key: {{ .Values.pgPasswordKey }}
            volumeMounts:
            - mountPath: /backup
              name: backup
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: {{ .Release.Name }}-pvc
          restartPolicy: Never
      backoffLimit: 3
