apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP  
