apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoservice-deployment
spec:
  selector:
    matchLabels:
      app: echoservice
  replicas: 1
  template:
    metadata:
      labels:
        app: echoservice
    spec:
      containers:
      - name: echoservice
        image: mtr.devops.telekom.de/magenta_canvas/public:echoservice 
        imagePullPolicy: Always
  
