apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: grafana
  labels:
    app: grafana
spec:
  gateways:
  - istio-ingress/k8s-gateway
  hosts:
  - 'grafana.k8s.{{ .Values.domainLabel1 }}.de'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: kube-prometheus-stack-grafana.grafana.svc.cluster.local
        port:
          number: 80
