apiVersion: v1
kind: Pod
metadata:
  annotations:
    hub.jupyter.org/username: feri
  creationTimestamp: "2023-02-26T11:13:41Z"
  labels:
    app: jupyterhub
    chart: jupyterhub-2.0.0
    component: singleuser-server
    heritage: jupyterhub
    hub.jupyter.org/network-access-hub: "true"
    hub.jupyter.org/servername: ""
    hub.jupyter.org/username: feri
    release: jupyter
  name: jupyter-feri
  namespace: spark
  resourceVersion: "11174522"
  uid: 80340b50-1711-48da-9c6c-f19ea6d68321
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: hub.jupyter.org/node-purpose
            operator: In
            values:
            - user
        weight: 100
  automountServiceAccountToken: false
  containers:
  - args:
    - jupyterhub-singleuser
    - --allow-root
    env:
    - name: GRANT_SUDO
      value: "yes"
    - name: JPY_API_TOKEN
      value: d91ebf4f891f4804b72b04ae306589d0
    - name: JUPYTERHUB_ACTIVITY_URL
      value: http://hub:8081/hub/api/users/feri/activity
    - name: JUPYTERHUB_ADMIN_ACCESS
      value: "1"
    - name: JUPYTERHUB_API_TOKEN
      value: d91ebf4f891f4804b72b04ae306589d0
    - name: JUPYTERHUB_API_URL
      value: http://hub:8081/hub/api
    - name: JUPYTERHUB_BASE_URL
      value: /
    - name: JUPYTERHUB_CLIENT_ID
      value: jupyterhub-user-feri
    - name: JUPYTERHUB_HOST
    - name: JUPYTERHUB_OAUTH_ACCESS_SCOPES
      value: '["access:servers!server=feri/", "access:servers!user=feri"]'
    - name: JUPYTERHUB_OAUTH_CALLBACK_URL
      value: /user/feri/oauth_callback
    - name: JUPYTERHUB_OAUTH_CLIENT_ALLOWED_SCOPES
      value: '[]'
    - name: JUPYTERHUB_OAUTH_SCOPES
      value: '["access:servers!server=feri/", "access:servers!user=feri"]'
    - name: JUPYTERHUB_SERVER_NAME
    - name: JUPYTERHUB_SERVICE_PREFIX
      value: /user/feri/
    - name: JUPYTERHUB_SERVICE_URL
      value: http://0.0.0.0:8888/user/feri/
    - name: JUPYTERHUB_USER
      value: feri
    - name: JUPYTER_IMAGE
      value: jupyterhub/k8s-singleuser-sample:2.0.0
    - name: JUPYTER_IMAGE_SPEC
      value: jupyterhub/k8s-singleuser-sample:2.0.0
    - name: MEM_GUARANTEE
      value: "1073741824"
    - name: NOTEBOOK_ARGS
      value: --allow-root
    image: jupyterhub/k8s-singleuser-sample:2.0.0
    imagePullPolicy: IfNotPresent
    lifecycle: {}
    name: notebook
    ports:
    - containerPort: 8888
      name: notebook-port
      protocol: TCP
    resources:
      requests:
        memory: "1073741824"
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/jovyan
      name: volume-feri
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - iptables
    - -A
    - OUTPUT
    - -d
    - 169.254.169.254
    - -j
    - DROP
    image: jupyterhub/k8s-network-tools:2.0.0
    imagePullPolicy: IfNotPresent
    name: block-cloud-metadata
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  nodeName: vmd38168.contaboserver.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: jupyter-user-scheduler
  securityContext:
    fsGroup: 100
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: hub.jupyter.org/dedicated
    operator: Equal
    value: user
  - effect: NoSchedule
    key: hub.jupyter.org_dedicated
    operator: Equal
    value: user
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: volume-feri
    persistentVolumeClaim:
      claimName: claim-feri
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-02-26T11:13:43Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-02-26T11:13:44Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-02-26T11:13:44Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-02-26T11:13:41Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://6389b50e04e0b0caeb25873e86f4228d318d69773f5fdb2d4ee0fd5466617f40
    image: docker.io/jupyterhub/k8s-singleuser-sample:2.0.0
    imageID: docker.io/jupyterhub/k8s-singleuser-sample@sha256:b4d6fa6915b78d502393fd15c995d4460414ffccd669afcfd7f417d0ecf9f1e5
    lastState: {}
    name: notebook
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-02-26T11:13:43Z"
  hostIP: 207.180.253.250
  initContainerStatuses:
  - containerID: containerd://1eb62d09d24d29d3083582455832dc9b28584c7f02c6fc4ea199306639f6ee9b
    image: docker.io/jupyterhub/k8s-network-tools:2.0.0
    imageID: docker.io/jupyterhub/k8s-network-tools@sha256:ab4172a025721495c0c65bd2a6165a6cd625bae39e0e5231c06e149c2ffc5dab
    lastState: {}
    name: block-cloud-metadata
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://1eb62d09d24d29d3083582455832dc9b28584c7f02c6fc4ea199306639f6ee9b
        exitCode: 0
        finishedAt: "2023-02-26T11:13:42Z"
        reason: Completed
        startedAt: "2023-02-26T11:13:42Z"
  phase: Running
  podIP: 10.244.0.139
  podIPs:
  - ip: 10.244.0.139
  qosClass: Burstable
  startTime: "2023-02-26T11:13:41Z"