# singleuser relates to the configuration of KubeSpawner which runs in the hub
# pod, and its spawning of user pods such as jupyter-myusername.
singleuser:
  uid: 0
  extraEnv:
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"
  cmd: start-singleuser.sh    
  image:
    # https://github.com/jupyter/docker-stacks/blob/main/pyspark-notebook/Dockerfile
    name: jupyter/pyspark-notebook
    tag: "spark-3.3.2"
  # https://z2jh.jupyter.org/en/latest/resources/reference.html#singleuser-allowprivilegeescalation
  allowPrivilegeEscalation: yes
  memory:
    guarantee: 4G
    
hub:
  config:
    Authenticator:
      admin_users:
        - feri
      #allowed_users:
      #  - user3
      #  - user4
    # ...
    DummyAuthenticator:
      password: katrIn
