---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: minio
  name: create-velero-user-and-buckets
  labels:
    app: minio
spec:
  template:
    metadata:
      name: create-velero-user-and-buckets
    spec:
      restartPolicy: Never
      volumes:
      - name: config
        emptyDir: {}
      containers:
      - name: mc
        image: minio/mc:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "mc alias set minio http://minio-api-service:80 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
           mc admin user add minio $VELERO_USER $VELERO_USER_PASSWORD;
           mc admin policy set minio readwrite user=$VELERO_USER;
           mc mb -p minio/velero-backup;
           mc mb -p minio/velero-snapshots"
        env:
        - name: MINIO_ROOT_USER
          value: admin
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-admin-secret
              key: admin-password        
        - name: VELERO_USER
          value: velerouser
        - name: VELERO_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: valerouser-secret
              key: velerouser-password        
