apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backup-pvc
  namespace: minecraft
  labels:
    app: minecraft-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
