apiVersion: v1
kind: Service
metadata:
  name: demoapp-service
  labels:
    app: demoapp
spec:
  type: ClusterIP
  selector:
    app: demoapp
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
