apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demoapp-vs
  labels:
    app: demoapp
spec:
  gateways:
  - istio-ingress/k8s-gateway
  hosts:
  - 'demoapp.k8s.{{ .Values.domainLabel1 }}.de'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: demoapp-service.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
