apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: k8s-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.k8s.{{ .Values.domainLabel1 }}.de'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*.k8s.{{ .Values.domainLabel1 }}.de'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: wc-k8s-tls
      mode: SIMPLE
