apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etherpad-data-pvc
  namespace: etherpad
  labels:
    app: etherpad
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
