apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-backup-pvc
  namespace: vaultwarden
  labels:
    app: vaultwarden-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
