apiVersion: v1
kind: Service
metadata:
  name: mc-forge-1-12-service
  namespace: minecraft
  labels:
    app: mc-forge-1-12
spec:
  type: LoadBalancer
  selector:
    app: mc-forge-1-12
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
  
