apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-ingress
  namespace: canvas
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production  
  labels:
    app: spark
spec:
  ingressClassName: nginx
  tls:
    - secretName: spark-ssl
      hosts:
      - keycloak.k8s.feri.ai              
  rules:
  - host: "spark.k8s.feri.ai"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: spark
              port:
                number: 8088
