---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: minio
  name: test-mc
  labels:
    app: minio
spec:
  template:
    metadata:
      name: test-mc
    spec:
      restartPolicy: Never
      volumes:
      - name: config
        emptyDir: {}
      containers:
      - name: mc
        image: minio/mc:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "sleep 3600"
        env:
        - name: MINIO_ROOT_USER
          value: admin
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-admin-secret
              key: admin-password        
        volumeMounts:
        - name: config
          mountPath: "/config"