apiVersion: v1
kind: Service
metadata:
  name: conjur-service
  namespace: conjur
  labels:
    app: conjur
spec:
  selector:
    app: conjur-oss
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP  
