# from https://medium.com/@rd.petrusek/kubernetes-istio-cert-manager-and-lets-encrypt-c3e0822a3aaf
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s2-cert
  namespace: istio-system
spec:
  secretName: k8s2-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "demoapp.k8s2.cluster-4.de"
    - "dashboard.k8s2.cluster-4.de"
    - "grafana.k8s2.cluster-4.de"
    - "jaeger.k8s2.cluster-4.de"
    - "kiali.k8s2.cluster-4.de"
    - "minecraft.k8s2.cluster-4.de"
    - "minio.k8s2.cluster-4.de"
    - "nexus.k8s2.cluster-4.de"
    - "s3.k8s2.cluster-4.de"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
    