apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minecraft
  name: minecraft-pvc
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
