apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: minecraft
  labels:
    app: minecraft
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
  
