apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: "itzg/minecraft-server:java8-multiarch"
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "FORGE"
        - name: VERSION
          value: "1.12.2"
        - name: FORGE_VERSION
          value: "14.23.5.2855"
        - name: MAX_MEMORY
          value: "4G"
        - name: MODPACK
          value: "https://filedn.eu/lwAjS7B5boTSPWN01fknj4b/mc-mods/mods.zip"
        - name: REMOVE_OLD_MODS
          value: "TRUE"
        #- name: OPS
        #  value: "patricklas,5ba3d1d5-92bd-3530-a98b-63fb3670230d,a86900d5-eed3-48d3-9162-00fdf0cec5f9"
        - name: OPS_FILE
          value: "/config/ops.json"
        - name: OP_PERMISSION_LEVEL
          value: "2"
        - name: SNOOPER_ENABLED
          value: "false"
        - name: ALLOW_FLIGHT
          value: "TRUE"
        - name: ONLINE_MODE
          value: "FALSE"
        - name: ENABLE_ROLLING_LOGS
          value: "true"
        - name: TZ
          value: "Europe/Berlin"
        - name: ENABLE_AUTOPAUSE
          value: "TRUE"
        - name: MAX_TICK_TIME
          value: "-1"
        - name: ICON
          value: "https://static.wikia.nocookie.net/pure-evil-wiki/images/b/b7/EmperorVitiate.png/revision/latest"
        - name: SERVER_NAME
          value: "PatMCS"
        - name: MOTD
          value: "The new PatMCS Server v1.12 with 26 mods"
        volumeMounts:
        - mountPath: /data
          name: data          
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-pvc
      - name: config
        configMap:
          name: minecraft-config

        
          
