apiVersion: batch/v1
kind: CronJob
metadata:
  name: nexus-backup-cronjob
  namespace: nexus
  labels:
    app: nexus-backup
spec:

spec:
  schedule: "30 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nexus-backup
            image: feridock/pgpcloudbackup:0.1
            command: [ "/bin/sh", "-c", "--" ]
            args: [ "echo starting nexus-backup;
            set -x;
            date;
            rm -rf /backup/nexus-data*.tgz;
            date;
            export TODAY=$(date -I);
            tar czf /backup/nexus-data-$TODAY.tgz -C /nexus-data .;
            date;
            /app/pgp-cloud-backup.sh;
            date;
            /app/pgp-cloud-housekeeping.sh;
            date;
            echo finished nexus-backup"]
            #securityContext:
            #  runAsUser: 0
            #  runAsGroup: 0            
            imagePullPolicy: IfNotPresent
            #imagePullPolicy: Always
            env:
            - name: PGPCB_CONFIG_FILE
              value: "/app/conf/.pcloud-config"
            - name: PGPCB_PUBLIC_PGP_KEY_FILE
              value: "/app/conf/encrypt-key.pub"
            - name: PGPCB_LOCAL_FOLDER
              value: "/backup"
            - name: PGPCB_TEMP_FOLDER
              value: "/tmp"
            - name: PGPCB_REMOTE_FOLDER
              value: "/VSERVERBACKUP/nexus"
            - name: PGPCB_DELETE_REMOTE
              value: "false"
            - name: PGPCB_KEEP_PERIODS
              value: "7d4w3m*y"
            - name: PGPCB_IGNORE_MISSING_TIMESTAMPS
              value: "false"
            volumeMounts:
            - mountPath: /backup
              name: backup
            - name: config
              mountPath: "/app/conf"
              readOnly: true
            - mountPath: /nexus-data
              name: nexus-data
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: nexus-backup-pvc
          - name: config
            secret:
              secretName: nexus-backup-secret
          - name: nexus-data
            persistentVolumeClaim:
              claimName: nexus-data-pvc
          restartPolicy: Never
      backoffLimit: 3
