nextcloud:
  #host: nextcloud.kube.home
  host: images.vps-2.cluster-4.de
  username: fhadmin
  #password: ****
  #trustedDomains: [images.vps-2.cluster-4.de]
  
persistence:
  # Nextcloud Data (/var/www/html)
  enabled: true
  size: 100Gi

