apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: wordpress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production  
  labels:
    app: wordpress
spec:
  ingressClassName: nginx
  tls:
    - secretName: wordpress-ssl
      hosts:
      - wordpress.k8s.feri.ai          
  rules:
  - host: "wordpress.k8s.feri.ai"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: wordpress
              port:
                number: 80

