apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mc-forge-1-12
  name: mc-forge-1-12-pvc
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
