apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-backup-pvc
  namespace: nexus
  labels:
    app: nexus-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
