apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hedgedoc-backup-pvc
  namespace: hedgedoc
  labels:
    app: hedgedoc-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
