apiVersion: batch/v1
kind: CronJob
metadata:
  name: hedgedoc-backup-sqldump-cronjob
  namespace: hedgedoc
  labels:
    app: hedgedoc-backup
spec:
  schedule: "45 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hedgedoc-backup-sqldump
            image: docker.io/bitnami/postgresql:15.2.0-debian-11-r14
            command: [ "/bin/sh", "-c", "--" ]
            args: [ "echo starting hedgedoc-backup-sqldump;
            sleep 3600;
            set -x;
            date;
            rm -rf /backup/hedgedoc-sqldump-*.sql.gz;
            date;
            export TODAY=$(date -I);
            cd /backup;
            pg_dump -h $POSTGRES_HOST -U $POSTGRES_USER | gzip -c > hedgedoc-sqldump-$TODAY.sql.gz;
            date;
            echo finished hedgedoc-backup-sqldump"]
            imagePullPolicy: IfNotPresent
            #imagePullPolicy: Always
            env:
            - name: POSTGRES_HOST
              value: hedgedoc-postgresql.hedgedoc.svc
            - name: POSTGRES_USER
              value: codimd
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: hedgedoc-postgresql
            volumeMounts:
            - mountPath: /backup
              name: backup
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: hedgedoc-backup-pvc
          restartPolicy: Never
      backoffLimit: 3
