apiVersion: batch/v1
kind: Job
metadata:
  name: vaultwarden-restore-job
  namespace: vaultwarden
  labels:
    app: vaultwarden-restore
spec:
      template:
        spec:
          containers:
          - name: vaultwarden-restore
            image: feridock/pgpcloudbackup:0.1
            command: [ "/bin/sh", "-c", "--" ]
            args: [ "echo waiting 10h;
            sleep 36000;
            echo finished"]
            securityContext:
              runAsUser: 0
              runAsGroup: 0            
            imagePullPolicy: IfNotPresent
            #imagePullPolicy: Always
            env:
            - name: PGPCB_CONFIG_FILE
              value: "/app/conf/.pcloud-config"
            - name: PGPCB_PRIVATE_PGP_KEY_FILE
              value: "/app/conf/.private-decrypt.key"
            - name: PGPCB_ENC_KEY_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-restore-secret
                  key: enc-passphrase
            - name: PGPCB_LOCAL_FOLDER
              value: "/restore"
            - name: PGPCB_REMOTE_FOLDER
              value: "/VSERVERBACKUP/vaultwarden"
            - name: PGPCB_FILTER_DATE
              value: ""
            - name: PGPCB_DELETE_LOCAL
              value: "true"
            - name: PGPCB_TEMP_FOLDER
              value: "/tmp"
            volumeMounts:
            - mountPath: /restore
              name: restore
            - name: config
              mountPath: "/app/conf"
              readOnly: true
            - mountPath: /vaultwarden-data
              name: vaultwarden-data
          volumes:
          - name: restore
            persistentVolumeClaim:
              claimName: vaultwarden-backup-pvc
          - name: config
            secret:
              secretName: vaultwarden-restore-secret
          - name: vaultwarden-data
            persistentVolumeClaim:
              claimName: vaultwarden
          restartPolicy: Never
      backoffLimit: 3
